describe('Login page',()=>{
    it('Enter value and sign in', ()=>{
        cy.visit('localhost:3000/login')
        cy.get('[id=email]').type('mithun@amrita.com')
        cy.get('[id=password]').type('123')
        cy.get('[id=submit]').click()
        cy.url().should('contain','/protected')
    })
    it('Enter Wrong password', ()=>{
        cy.visit('localhost:3000/login')
        cy.get('[id=email]').type('mithun@amrita.com')
        cy.get('[id=password]').type('1234')
        cy.get('[id=submit]').click()
        cy.get('[id=chakra-toast-manager-bottom]').should('contain','Login Failure')
    })
    it('Enter Wrong password', ()=>{
        cy.visit('localhost:3000/login')
        cy.get('[id=email]').type('mithun@amrita.com')
        cy.get('[id=password]').type('1234')
        cy.get('[id=submit]').click()
        cy.get('[id=chakra-toast-manager-bottom]').should('contain','Login Failure')
    })
    it('Enter wrong email', ()=>{
        cy.visit('localhost:3000/login')
        cy.get('[id=email]').type('mithun2@amrita.com')
        cy.get('[id=password]').type('1234')
        cy.get('[id=submit]').click()
        cy.get('[id=chakra-toast-manager-bottom]').should('contain','Cannot read property')
    })
    it('Enter value and sign in as admin', ()=>{
        cy.visit('localhost:3000/login')
        cy.get('[id=email]').type('admin@admin.com')
        cy.get('[id=password]').type('123')
        cy.get('[id=role]').select('Admin')
        cy.get('[id=submit]').click()
        cy.url().should('contain','/protected')
    })
})
