describe('Login page',()=>{
    it('Navigating to leave page', ()=>{
        cy.visit('localhost:3000/login')
        cy.get('[id=email]').type('mithun@amrita.com')
        cy.get('[id=password]').type('123')
        cy.get('[data-testid=submit]').click()
        cy.url().should('contain','/protected')
        cy.get('button').contains('Apply Leave').click()
        cy.url().should('contain','/protected/leave')
    })
    it('Viewing Applied leaves', ()=>{
        cy.visit('localhost:3000/login')
        cy.get('[id=email]').type('mithun@amrita.com')
        cy.get('[id=password]').type('123')
        cy.get('[data-testid=submit]').click()
        cy.url().should('contain','/protected')
        cy.get('button').contains('Apply Leave').click()
        cy.url().should('contain','/protected/leave')
        cy.get('button').contains('VIEW LEAVES').click()
    })
    it('Applying leave and then checking applied leave', ()=>{
        cy.visit('localhost:3000/login')
        cy.get('[id=email]').type('mithun@amrita.com')
        cy.get('[id=password]').type('123')
        cy.get('[data-testid=submit]').click()
        cy.url().should('contain','/protected')
        cy.get('button').contains('Apply Leave').click()
        cy.url().should('contain','/protected/leave')
        cy.get('[id=leavetype]').select('Medical')
        cy.get('[id=fromdate]').click().get('button').contains('7').click()
        cy.get('button').contains('OK').click()
        cy.get('[id=todate]').click().get('button').contains('10').click()
        cy.get('button').contains('OK').click()
        cy.get('[id=apply]').contains('Apply').click()
        cy.get('[id=chakra-toast-manager-bottom]').should('contain','Leave apply success')
        cy.get('button').contains('VIEW LEAVES').click()
    })
    
})