describe('Checking basic admin scheduling functionalities', ()=>{
    it('Enter value and sign in as admin and reach events page', ()=>{
        cy.visit('localhost:3000/login')
        cy.get('[id=email]').type('admin@admin.com')
        cy.get('[id=password]').type('123')
        cy.get('[id=role]').select('Admin')
        cy.get('[id=submit]').click()
        cy.url().should('contain','/protected')
        cy.get('button').contains('Calendar').click()
        cy.url().should('contain','/protected/Calendar')
        cy.get('button').contains('SEMESTER DETAILS').click()
        cy.get('[data-testid=SemId]').type('SEM_5_2021')
        cy.get('[id=semNo]').select('7')
        cy.get('label').contains('startDate').click().get('button').contains('7').click()
        cy.get('button').contains('OK').click()
        cy.get('label').contains('endDate').click().get('button').contains('10').click()
        cy.get('button').contains('OK').click()
        cy.get('button').contains('Add Semester').click()
        cy.get('[id=chakra-toast-manager-bottom]').should('contain','Semester SEM_5_2021 create success')
    })
})
