describe('Checking basic admin user management functionalities', ()=>{
    it('Enter value and sign in as admin and create new user', ()=>{
        cy.visit('localhost:3000/login')
        cy.get('[id=email]').type('admin@admin.com')
        cy.get('[id=password]').type('123')
        cy.get('[id=role]').select('Admin')
        cy.get('[id=submit]').click()
        cy.url().should('contain','/protected')
        cy.get('[data-testid=email]').type('test_user203@amrita.com')
        cy.get('[data-testid=username]').type('test_user_103')
        cy.get('[type="checkbox"]').check("Faculty")
        cy.get('button').contains('Create and send e-mail to the user').click()
        cy.get('[id=chakra-toast-manager-bottom]').should('contain','Account Creation Success')
    })
    it('View created users', ()=>{
        cy.visit('localhost:3000/login')
        cy.get('[id=email]').type('admin@admin.com')
        cy.get('[id=password]').type('123')
        cy.get('[id=role]').select('Admin')
        cy.get('[id=submit]').click()
        cy.url().should('contain','/protected')
        cy.get('button').contains('VIEW ACCOUNTS').click()
        cy.get('td').contains('test_user_103')
    })
    //cy.get('div').should('have.class', 'chakra-input__group css-4302v8').and('have.css', 'color'. 'red')
})
