describe('Checking basic admin calendar functionalities', ()=>{
    it('Enter value and sign in as admin and edit day type', ()=>{
        cy.visit('localhost:3000/login')
        cy.get('[id=email]').type('admin@admin.com')
        cy.get('[id=password]').type('123')
        cy.get('[id=role]').select('Admin')
        cy.get('[id=submit]').click()
        cy.url().should('contain','/protected')
        cy.get('button').contains('Calendar').click()
        cy.url().should('contain','/protected/Calendar')
        cy.get('button').contains('EDIT DAY TYPE').click()
        cy.get('label').contains('date').click().get('button').contains('7').click()
        cy.get('button').contains('OK').click()
        cy.get('label').contains('Holiday').click()
        cy.get('button').contains('Add Day Type').click()
        cy.get('[id=chakra-toast-manager-bottom]').should('contain','type create success')
    })
    it('Enter value and sign in as admin and edit class period', ()=>{
        cy.visit('localhost:3000/login')
        cy.get('[id=email]').type('admin@admin.com')
        cy.get('[id=password]').type('123')
        cy.get('[id=role]').select('Admin')
        cy.get('[id=submit]').click()
        cy.url().should('contain','/protected')
        cy.get('button').contains('Calendar').click()
        cy.url().should('contain','/protected/Calendar')
        cy.get('button').contains('EDIT CLASS PERIODS').click()
        cy.get('[id=select_fac]').select('mithun')
        cy.get('[id=select_sem]').select('SEM_5_2021')
        cy.get('[id=day]').select('Tuesday')
        cy.get('[data-testid=coursecode]').type('15CSE361')
        cy.get('[id=startTime-label]').click()
        cy.get('.MuiPickersClock-squareMask').click('topRight');
        cy.get('.MuiPickersClock-squareMask').click('bottom');
        cy.get('button').contains('OK').click()
        cy.get('[id=endTime]').click()
        cy.get('.MuiPickersClock-squareMask').click(250, 120);
        cy.get('.MuiPickersClock-squareMask').click('bottom');
        cy.get('button').contains('OK').click()
        cy.get('button').contains('Add Period').click()
        cy.get('[id=chakra-toast-manager-bottom]').should('contain','Period 15CSE361 create success')
    })
})
