describe('Checking Usability of the Calendar page for User', ()=>{
  it('Enter value and sign in as admin and edit day type', ()=>{
      cy.visit('localhost:3000/login')
      cy.get('[id=email]').type('mithun@amrita.com')
      cy.get('[id=password]').type('123')
      cy.get('[id=role]').select('Faculty')
      cy.get('[id=submit]').click()
      cy.url().should('contain','/protected')
      cy.get('button').contains('Calendar').click()
      cy.url().should('contain','/protected/Calendar')
      cy.get('[class=rbc-toolbar-label]').should('contain','June 2021')
      cy.get('button').contains('Next').click()
      cy.get('[class=rbc-toolbar-label]').should('contain','July 2021')
      cy.get('[type=button]').contains('Back').click()
      cy.get('[type=button]').contains('Back').click()
      cy.get('[class=rbc-toolbar-label]').should('contain','May 2021')
      cy.get('[type=button]').contains('Next').click()
      cy.get('[type=button]').contains('Day').click()
      cy.get('[class=rbc-toolbar-label]').should('contain','Wednesday Jun 09')
      cy.get('[type=button]').contains('Week').click()
      cy.get('[class=rbc-toolbar-label]').should('contain','June 06 – 12')
      cy.get('[type=button]').contains('Work Week').click()
      cy.get('[class=rbc-toolbar-label]').should('contain','June 07 – 11')
      cy.get('[type=button]').contains('VIEW PERIODS').click()
      cy.get('[id=select_sem]').select('SEM_5_2021')
      cy.get('td').should('contain','15CSE361')
  })
})
