describe('Checking the remainder and notification functionalities', ()=>{
  it('sign in as a user and check for the functionality of setting a remainder for an event ', ()=>{
      cy.visit('localhost:3000/login')
      cy.get('[id=email]').type('mithun@amrita.com')
      cy.get('[id=password]').type('123')
      cy.get('[id=role]').select('Faculty')
      cy.get('[id=submit]').click()
      cy.url().should('contain','/protected')
      cy.get('button').contains('Calendar').click()
      cy.url().should('contain','/protected/Calendar')
      cy.get('[class=rbc-toolbar-label]').should('contain','June 2021')
      cy.get('[type=button]').contains('Back').click()
      cy.get('[type=button]').contains('Back').click()
      cy.get('[type=button]').contains('Back').click()
      cy.get('[class=rbc-event-content]').contains('Reminder Test').click()
      cy.get('[id=select_rem]').select('2 mins before')
      cy.get('[type=button]').contains('Set Reminder').click()
      cy.get('[id=chakra-toast-manager-bottom]').should('contain','Reminder set success')
      cy.get('[type=button]').contains('Agenda').click()
      cy.get('td').should('contain','Reminder Test')
  })
})
